### ISSUE TITLE
[display real data] fetch real results

### ISSUE THREAD

**Issue by giogonzo** [nerder/gh-explorer#21]
<- #22 
## requirements
- when the user clicks on the search button, we should ask for results from github.
  - You can choose the precise api and parameters (probably `https://api.github.com/search/repositories`)
- for each result, we should show the repo name and description
- each repo name should also link (in a separate window) to the github.com page
## specs
- you should use axios to make http calls
- probably you want to keep api calls to a separate file e.g. `api.js` and export functions from there (each one should return a promise)
- TODO complete here with the final api parameters

**Comment by nerder** [comment]
@giogonzo i edit the title just to make it clear

**Comment by giogonzo** [comment]
:+1: whoops probably forgot to save before :P
