### ISSUE TITLE
create the app routes

### ISSUE THREAD

**Issue by giogonzo** [nerder/gh-explorer#3]
## requirements
- the app should be organized in two routes (in terms of react-router):
  - one for the main view (list of results)
  - one for the detail view (details of each result/repo)
## specs
- just define an appropriate routes structure and put dummy placeholder content for each one
- Create 2 routes
- The second route accept params
- Linking to the correct route and come back to home route

**Comment by nerder** [comment]
@giogonzo 
When you say two routes, you mean except the '/' one?
Even a notFound route can be useful.

This paper could be used as a very good starting point: https://www.themarketingtechnologist.co/react-router-an-introduction/

**Comment by giogonzo** [comment]
yes the two "routes" (or views, or states of our app) will be the "list view" and the "detail view"

the fact that the detail view will be a modal opened on top of the other one is a non-strictly-related concept but it is in terms of react router: when you render the "detail" view you have to do it visually on top of the other one, meaning they both should be visible at the same time, meaning one of the 2 should be nested in the other

**Comment by giogonzo** [comment]
> When you say two routes, you mean except the '/' one?

yes you need to have a single top level wrapper. That could be either one of the two routes or a third "empty" one

> Even a notFound route can be useful.

yes, definitely, but not in the scope of this issue ;)
