### ISSUE TITLE
[main page] first iteration

### ISSUE THREAD

**Issue by FrancescoCioria** [nerder/gh-explorer#7]
## requirements

scope of the iteration:
- implement the page layout
  - nav bar
    - left: app name
    - center: search component
    - right: empty
  - results panel
    - should be a floating panel
## sub-issues
- [x] main layout structure #8 
- [x] implement NavBar #9 
- [x] implement ResultsPanel #11 
## mockup

![image](https://cloud.githubusercontent.com/assets/4029499/12507566/d5aacfac-c0f6-11e5-8ed4-ed8411e97214.png)

**Comment by giogonzo** [comment]
@nerder remember: we don't care about the actual functionality and data now, just about the layout. So all the data should be mocked for the time being

**Comment by nerder** [comment]
@giogonzo ok i perfectly got it :ok_hand:

**Comment by nerder** [comment]
All the child issues are done. If ok i'll close this @giogonzo @FrancescoCioria

**Comment by FrancescoCioria** [comment]
:+1:
