### ISSUE TITLE
main layout structure

### ISSUE THREAD

**Issue by FrancescoCioria** [nerder/gh-explorer#8]
<- #7 
## requirements

The scope of this issue is to simply define the layout. No logic, style nor sub-components (like `SearchBar` or `ResultsPanel` should be implemented)
- page should not scroll vertically (the scroll will be inside the `ResultsPanel` itself)
- main content (future `ResultsPanel` will be inside it) is centered horizontally
- main content should grow horizontally, but no higher than `1000 px`
- main content should grow vertically (we want it to fill the available vertical space)

for the mockup refer to #7 
## specs
- use `FlexView` for basic layout (https://github.com/buildo/react-components/tree/master/src/flex)
- consider using `NavBar` (https://github.com/buildo/react-components/tree/master/src/nav-bar)

**Comment by nerder** [comment]
I found out this 2 resources that can help me understand <b>Flexbox</b>:
- <a href="https://css-tricks.com/snippets/css/a-guide-to-flexbox/">A Complete Guide to Flexbox</a>
- <a href="http://flexboxfroggy.com/">FLEXBOX FROGGY </a>

PS: Thanks to @FrancescoCioria for the learning by doing course.

**Comment by giogonzo** [comment]
nice!

consider you shouldn't need to use flexbox directly since we have the super handy `FlexView` component linked above ;)

**Comment by nerder** [comment]
<img width="1279" alt="screen shot 2016-01-22 at 16 41 07" src="https://cloud.githubusercontent.com/assets/3502356/12515117/05706f0a-c127-11e5-8fa8-099b31ae44ae.png">

Ok, now i think i get how <b>flexbox</b> work :+1: 
Now i can use FlexView component without any problem (i hope)

**Comment by FrancescoCioria** [comment]
also, have a look at this `README` : https://github.com/buildo/react-components/tree/master/src/flex
the docs are still a _work in progress_, but I think you can already find them useful (the table shows the custom `props` for `FlexView` with a short description)
